### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by m4tx** [KSIUJ/mordor#12]
I believe we should have some sort of user management panel for admins that would allow to assign roles to users.

**Comment by zielmicha** [comment]
Maybe we should integrate some admin-like tool like JHipster? Having web admin panel is nice anyway (e.g. to debug things).

**Comment by apardyl** [comment]
@zielmicha AFAIK JHipster is not an admin tool, but a full stack application generator. It does not integrate with existing applications.

**Comment by apardyl** [comment]
@m4tx ping
