### ISSUE TITLE
Basic error handling

### ISSUE THREAD

**Issue by apardyl** [KSIUJ/mordor#15]
Create error pages:
* application error page (replace the default /error fallback page),
* 404 page,
* 403 page (possibly differentiate between unauthenticated session and lack of permissions)

**Comment by wjcsz** [comment]
What is left to do @apardyl? 403 page and "application error page"?

**Comment by apardyl** [comment]
> What is left to do @apardyl? 403 page and "application error page"?

404 and 403. Default fallback page/application error has been implemented in 34bca3daef49282ba43f040fb77e9a19c0abeb8a
